name: 🚀 Déploiement Azure

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: 🚀 Déployer sur la VM Azure
    runs-on: self-hosted
    steps:
      - name: Déployer avec Docker Compose
        run: |
          cd ~/cesizen
          git fetch origin main
          git reset --hard origin/main
          docker compose --env-file .env.azure -f docker-compose.yml -f docker-compose.azure.yml up -d --build
          docker compose --env-file .env.azure -f docker-compose.yml -f docker-compose.azure.yml exec -T app php bin/console doctrine:migrations:migrate --no-interaction